version: '3.8'
services:
    database:
        container_name: dev-corelight
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: nopassword
          POSTGRES_DB: store-store
        networks: 
          - fullstack

    cron:
        image: golang:1.16.3-alpine
        volumes: 
            - .:/go/src/corelightfx
        working_dir: /go/src/corelightfx
        command: go run ./cmd/cron/main.go
        networks: 
            - fullstack
        depends_on: 
            - database
    
    # web:
    #    image: golang:1.16.3-alpine
    #    volumes: 
    #       - .:/go/src/corelightfx
    #    working_dir: /go/src/corelightfx
    #    command: go run ./cmd/rest-api/main.go 

networks: 
    fullstack:
        driver: bridge            

    
  